version: '3'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000

    depends_on:
      - db        

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: signup_login
      MYSQL_USER: mayur
      MYSQL_PASSWORD: mayur
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql



  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
volumes:
  db_data:
